// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package srv

import (
	"project/api/v1"
	"project/configs"
	"project/internal/app/srv/grpc"
	"project/internal/app/srv/http"
	"project/internal/app/srv/http/hdl"
	"project/internal/databases"
	"project/internal/initializer"
	"project/internal/repo"
)

// Injectors from wire.go:

func RunSrv() (*App, error) {
	viper, err := configs.NewConfig()
	if err != nil {
		return nil, err
	}
	data, err := databases.InitDB(viper)
	if err != nil {
		return nil, err
	}
	dbInitializer := &repo.DbInitializer{
		Db: data,
	}
	userClient := proto.HelloRpcClient(viper)
	users := &hdl.Users{
		UserClient: userClient,
	}
	hdlHdl := &hdl.Hdl{
		Hello: users,
	}
	engine := initializer.DefaultGin()
	httpInitializer := &http.Initializer{
		Hdl:    hdlHdl,
		Router: engine,
	}
	userService := &grpc.UserService{}
	grpcInitializer := &grpc.Initializer{
		Config:      viper,
		UserService: userService,
	}
	bootloader := &Bootloader{
		DbInitializer:   dbInitializer,
		HttpInitializer: httpInitializer,
		GrpcInitializer: grpcInitializer,
	}
	app := &App{
		Configs:    viper,
		Bootloader: bootloader,
		DB:         data,
	}
	return app, nil
}
