// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package srv

import (
	"project/configs"
)

// Injectors from wire.go:

func RunSrv() (*App, func(), error) {
	viper, err := configs.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	app := &App{
		Configs: viper,
	}
	return app, func() {
	}, nil
}
