// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"week4/config"
	"week4/internal/biz"
	"week4/internal/data"
	"week4/internal/server"
)

// Injectors from wire.go:

func InitServer() (*server.UserServer, error) {
	viper, err := config.InitConfig()
	if err != nil {
		return nil, err
	}
	dataData, err := data.NewDB(viper)
	if err != nil {
		return nil, err
	}
	userDaoInf := data.NewInMemoUserDao(dataData)
	userService := biz.NewUserService(userDaoInf)
	grpcServer := server.NewGrpcServer(userService)
	httpServer := server.NewHttpServer(userService)
	configConfig := config.NewConfig(viper)
	userServer := server.NewUserServer(grpcServer, httpServer, configConfig)
	return userServer, nil
}
